FROM node:22-slim

WORKDIR /app

# copy only dependency files first (for caching)
COPY package.json package-lock.json ./
COPY apps/ingestion-service/package.json apps/ingestion-service/
COPY apps/websocket-service/package.json apps/websocket-service/
COPY apps/agent-service ./apps/agent-service
COPY packages/shared/package.json packages/shared/

# install ALL workspace deps
RUN npm install

# copy source later (but in dev this will be overridden by bind mount)
COPY . .

CMD ["npm", "run", "websocket:dev"]