services:

  redis:
    image: redis:7
    container_name: redis
    mem_limit: 200m

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    command: redis-server --appendonly yes

  ingestion-service:
    build:
      context: .
      dockerfile: apps/ingestion-service/Dockerfile

    container_name: ingestion-service
    mem_limit: 700m

    ports:
      - "4001:4001"

    environment:
      NODE_OPTIONS: "--max-old-space-size=512"

    env_file:
      - .env

    depends_on:
      - redis

  websocket-service:
    build:
      context: .
      dockerfile: apps/websocket-service/Dockerfile

    container_name: websocket-service
    mem_limit: 300m

    ports:
      - "4000:4000"

    environment:
      NODE_OPTIONS: "--max-old-space-size=256"

    env_file:
      - .env

    depends_on:
      - redis

volumes:
  redis_data: