FROM node:22-slim

WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/ingestion-service/package.json apps/ingestion-service/
COPY apps/websocket-service/package.json apps/websocket-service/
COPY packages/shared/package.json packages/shared/

RUN npm install

RUN npx playwright install --with-deps chromium

COPY . .

CMD ["npm", "run", "ingestion:dev"]